Update `Github` @@arrow
OpenInterpreter/open-interpreter pull request #1108
Opened 2024-03-22 05:56 UTC by arisacoba

### Describe the changes you have made:

### Reference any relevant issues (e.g. "Fixes #000"):

### Pre-Submission Checklist (optional but appreciated):

- [ ] I have included relevant documentation updates (stored in /docs)
- [ ] I have read `docs/CONTRIBUTING.md`
- [ ] I have read `docs/ROADMAP.md`

### OS Tests (optional but appreciated):

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux

2024-03-22 17:35 UTC, Notnaton requested changes

2024-03-22 17:35 UTC, Notnaton commented on docs/CONTRIBUTING.md
> +There are many ways to contribute, from helping others on [GitHub](https://github.com/KillianLucas/open-interpreter/issues) or [Discord](https://discord.gg/6p3fD6rBVm), writing documentation, or impr
edit link to: https://github.com/OpenInterpreter/open-interpreter/issues

2024-03-23 15:24 UTC, MikeBirdTech commented on docs/CONTRIBUTING.md
> +There are many ways to contribute, from helping others on [GitHub](https://github.com/OpenInterpreter/open-interpreter/issues) or [Discord](https://discord.gg/6p3fD6rBVm), writing documentation, or i
```suggestion
There are many ways to contribute, from helping others on [GitHub](https://github.com/OpenInterpreter/open-interpreter/issues) or [Discord](https://discord.gg/Hvz9Axh84z), writing documentation, or improving code.

```

2024-03-23 15:25 UTC, MikeBirdTech approved these changes
Thanks for the PR @arisacoba!

2024-03-27 20:12 UTC, merged